name: flutter_date_pickers
description: Flutter package for day, week, range and month date pickers.
version: 0.1.8
author: Maria Melnik <melnikmk@gmail.com>
homepage: https://github.com/MariaMelnik/flutter_date_pickers
issue_tracker: https://github.com/MariaMelnik/flutter_date_pickers/issues

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.16.1
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
